### ISSUE TITLE
Posts Management

### ISSUE THREAD

**Issue by charbelfakhry** [charbelfakhry/csis_279_fall_23_nest#8]

**Comment by charbelfakhry** [comment]
CRUD for Posts
Including Services and Controllers.

**Comment by aboudekahil** [comment]
Hello, for the posts.

`POST /posts` (body: all the post infos)
`GET /:username/:postid` (username query param for post's user and post id same thing but for which post)
`DELETE /:username/:postid` (to delete a post)

use the jwt to get the user id of the poster.

Thank you
